name: Testing check version

on:
  push:
    branches: [ "master" ]

jobs:
  check-tag:
    name: Check Version
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get current version
        run: |
          echo "APP_VERSION=$(grep -E -o 'v[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)" >> $GITHUB_ENV
          echo $APP_VERSION
