name: Create Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Get Tag from Dockerfile
      #   run: |
      #     APP_VERSION=$(grep -E -o 'v[0-9]+\.[0-9]+\.[0-9]+' Dockerfile) >> $GITHUB_ENV
      #     echo $APP_VERSION

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        run: |
          APP_VERSION=$(grep -E -o 'v[0-9]+\.[0-9]+\.[0-9]+' Dockerfile) >> $GITHUB_ENV
          echo $APP_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: $APP_VERSION
          release_name: Release $APP_VERSION
          
